KE 387: GHCJS FFI post first draft
input-output-hk/engineering pull request #14
Opened 2022-08-19 18:30 UTC by doyougnu

I'm unsure about the safety check section. In particular I don't think GHCJS performs a check comparing the type signature to the string payload of in an FFI invocation....

2022-08-22 08:56 UTC, hsyl20 requested changes
Good. Only a simple change required.

Could you also add a link to https://github.com/ghcjs/ghcjs/blob/master/doc/foreign-function-interface.md for reference

2022-08-22 08:56 UTC, hsyl20 commented on blog/2022-08-18-ghcjs-ffi.md
> +`h$base_fstat(...)` for the code generator to use when compiling. Compare this
you probably have changed the example because it's no longer interruptible, nor `fstat`

2022-08-22 15:28 UTC, doyougnu commented on blog/2022-08-18-ghcjs-ffi.md
> +`h$base_fstat(...)` for the code generator to use when compiling. Compare this
ah I did do exactly that. Great catch!

2022-08-22 15:29 UTC, doyougnu commented on blog/2022-08-18-ghcjs-ffi.md
> +`h$base_fstat(...)` for the code generator to use when compiling. Compare this
resolved in 5c2f82e

2022-08-25 08:53 UTC, hsyl20 approved these changes

2022-08-25 08:53 UTC, hsyl20 commented
LGTM.
@luite @JoshMeredith could you review?

2022-10-06 09:26 UTC, merged