One step forward, an easier interoperability between Rust and Haskell
input-output-hk/engineering pull request #23
Opened 2022-12-16 13:44 UTC by yvan-sraka

This is a short introduction article to sum up the why and how of [`cargo-cabal`](https://github.com/yvan-sraka/cargo-cabal) and [`hs-bindgen`](https://github.com/yvan-sraka/hs-bindgen).

I got already reviewed by @hsyl20 (Sylvain) and @iquerejeta (Iñigo):

- Sylvain suggested that I add a short answer to the question “What would be the reason to NOT use these tools”. After thinking a bit about it, I wonder if I could mention that `CApiFFI` features, like using C values that are `#define` in a header or `vargs`, are not supported (because they're indeed C specific). E.g. variadic arguments didn't exist in Rust and are usually implemented with [the Builder pattern](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html). Is this obvious or not that if you're looking for `CApiFFI` features you should embed Rust code in a C library (with e.g. `c-bindgen`, and so not use the tools introduced here)?

- Iñigo recommend me to rework a paragraph I wrote mentioning _[Cap’n Proto](https://capnproto.org/): based on memory sharing, prevents (de)serialization cost by offering a common cross-language custom memory mapping. Each language should use the SDK provided to read/write to it, based on RPC communication primitives, to prevent most of the synchronization issues that comes with shared resources approaches_. This is actually IMO a (good) alternative to FFI, with which I should experiment (there is already a [Haskell](https://github.com/zenhack/haskell-capnp) and a [Rust](https://github.com/capnproto/capnproto-rust) implementation), so not sure if I rather should mention it in conclusion?

All feedbacks are welcome, both on article structure, clarity, typos, etc… I plan to merge it like one week or two after Christmas and New eve break, so there is no rush 🎄

2022-12-22 12:21 UTC, hsyl20 reviewed
Just a few suggestions for now. I'll continue to review the rest next year

2022-12-22 12:21 UTC, hsyl20 commented on blog/2023-01-02-hs-bindgen-introduction.md
> +Here at IOG, we maintain big Haskell codebases that we want to make rely on some Rust dependencies.
```suggestion
At IOG we maintain large Haskell codebases and we would like to interface them with some libraries written in Rust.
```

Perhaps also a good place to introduce Rust. You're more informed than me but something like this could do:

```
Rust is a relatively new programming language that offers very good performance (comparable to programs written in C) with strong static typing guarantees (similarly to Haskell's). The main difference with Haskell is that there is no garbage collection (the memory must be handled explicitly): that's the reason why programs are usually faster but also more cumbersome to write than with Haskell.
```

2022-12-22 12:21 UTC, hsyl20 commented on blog/2023-01-02-hs-bindgen-introduction.md
> +E.g., for cryptographic primitives, which was the first use case that Iñigo (Cardano Lead Cryptography Engineer) brings me: his concerns were to use [`sha3`](https://crates.io/crates/sha3) crate (Rus
```suggestion
One typical use case concerns cryptographic primitives which must be very performant. The first use case that Iñigo NAME (Cardano Lead Cryptography Engineer) brought me consisted in replacing a cryptographic library used by `cardano-base`. Namely, replacing `cryptonite`, a library written in Haskell and C, with [`sha3`](https://crates.io/crates/sha3), a Rust library (or "crate").
```

2022-12-22 12:21 UTC, hsyl20 commented on blog/2023-01-02-hs-bindgen-introduction.md
> +> Solving the [interoperability](https://docs.rust-embedded.org/book/interoperability/) problem means deciding on what protocol to use to communicate and share data-structure across different runtime
```suggestion
> Solving the [interoperability](https://docs.rust-embedded.org/book/interoperability/) problem means:
> 1. designing a protocol that allows two codes written with different languages and using different runtime systems to communicate
> 2. designing tools and methods to build, to bundle, and to distribute such polyglot code bases (what developers fear most)
```

2023-01-02 09:28 UTC, yvan-sraka commented
Thanks for your feedback and fixes @hsyl20! I can add you and @iquerejeta to authors since you really help me to write it, I don't know what's the usual policy on this blog?

I think before merging I would (side to other reviews / feedbacks) like to rework both the Rust language introduction you suggested and both the numerous links I gave as references that are a bit messy! Likewise, I was in particular thinking about adding to the list https://github.com/rust-lang/rust/pull/105586 and https://frasertweedale.github.io/blog-fp/posts/2022-09-23-ffi-safety-and-gc.html

2023-01-05 10:56 UTC, angerman approved these changes

2023-01-05 10:56 UTC, angerman commented on blog/2023-01-02-hs-bindgen-introduction.md
> +This list isn't exhaustive but give you a big hint, all these projects are about bindgen!
~big~, generating bindings (bindgen).

2023-01-05 10:56 UTC, angerman commented on blog/2023-01-02-hs-bindgen-introduction.md
> +* Generate a custom `X.cabal` linking `rustc` output as `extra-librairies`, and either a ([`naersk`](https://github.com/nix-community/naersk) and [`haskell.nix`](https://github.com/input-output-hk/ha
Does it need to be a Setup.lhs? Are we using literate haskell for specific reasons?

2023-01-05 14:13 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +* Generate a custom `X.cabal` linking `rustc` output as `extra-librairies`, and either a ([`naersk`](https://github.com/nix-community/naersk) and [`haskell.nix`](https://github.com/input-output-hk/ha
No, it could completely be a `Setup.hs`! I just choose to generate literate haskell because I wanted to have a way to differentiate my writings around code of [the Rust build automation commented by default](https://github.com/yvan-sraka/cargo-cabal/blob/main/src/Setup.lhs#L62-L76)!

2023-01-16 16:38 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +Rust is a relatively new programming language that offers very good performance (comparable to programs written in C) with strong static typing guarantees (similarly to Haskell's). The main differenc
```suggestion
Rust is a systems programming language known for its strong static typing guarantees, which make it similar to Haskell (even if a bit less expressive). However, unlike Haskell, Rust does not have a GC (Garbage Collector) and use a compile-time memory management strategy. This mechanism is encoded through its type system with the concept of _“ownership”_ and _“lifetime”_ of values, which can complicate the writing of programs but unlock smaller runtime costs footprint. Rust is becoming increasingly popular in the systems programming and embedded systems domains, and is also used in areas such as cryptography, where performance is critical.
```

2023-01-16 16:48 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +Thanks for reading, feel free to experiment with this Proof of Concept and to provide feedbacks on GitHub :)
I was thinking of giving a list of reference of this form (rather than a bunch of linking hidden in the article corpus), I don't know, what are your thoughts about it?

```suggestion
Thanks for reading, feel free to experiment with this Proof of Concept and to provide feedbacks on GitHub :)

## References

Unordered list of links to go further:

- [`cargo-cabal`](https://github.com/yvan-sraka/cargo-cabal): A CLI tool for turning a Rust crate into an Haskell package.
- [`hs-bindgen`](https://github.com/yvan-sraka/hs-bindgen): A tool for generating FFI bindings between Rust and Haskell.
- [`rust-bindgen`](https://github.com/rust-lang/rust-bindgen): A tool for generating FFI bindings between Rust and C.
- [`c-bindgen`](https://github.com/eqrion/cbindgen): A tool for generating FFI bindings between C and Rust.
- [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen): A tool for generating FFI bindings between Rust and JavaScript.
- [`cryptonite`](https://github.com/input-output-hk/cardano-crypto/blob/develop/cbits/cryptonite_sha512.h): Cryptographic library used by `cardano-base`.
- [`sha3`](https://crates.io/crates/sha3): A Rust library for sha3 cryptographic primitive.
- [Rust FFI documentation](https://doc.rust-lang.org/nomicon/ffi.html): Foreign Function Interface (FFI) in Unsafe Rust (nomicon) guide.
- [`#[no_mangle]` attribute](https://doc.rust-lang.org/reference/abi.html#the-no_mangle-attribute): An attribute in Rust to prevent symbol mangling.
- [`rustc` linkage](https://doc.rust-lang.org/reference/linkage.html): The process of linking object files together to form an executable program in Rust.
- [`#[repr(interop)]`](https://github.com/rust-lang/rust/pull/105586): Experimental feature gate proposal `interoperable_abi`.
- [_"FFI safety and GC"_ by Fraser Tweedale](https://frasertweedale.github.io/blog-fp/posts/2022-09-23-ffi-safety-and-gc.html): A blog post discussing FFI safety and Garbage Collection in Haskell.
- [Unix Domain Socket](https://en.wikipedia.org/wiki/Unix_domain_socket): A type of inter-process communication socket that allows communication between processes on the same machine.
- [Google Protobuf](https://developers.google.com/protocol-buffers): A protocol for data serialization and communication.
- [Cap'n Proto](https://capnproto.org/): A data interchange format and capability-based RPC system.
- [Haskell Cap'n Proto](https://github.com/zenhack/haskell-capnp): A Haskell implementation of Cap'n Proto.
- [Rust Cap'n Proto](https://github.com/capnproto/capnproto-rust): A Rust implementation of Cap'n Proto.
```

2023-01-17 08:14 UTC, hsyl20 commented on blog/2023-01-02-hs-bindgen-introduction.md
> +#[hs_bindgen]
Is there a way to specify that we want to generate a `safe` or `unsafe` foreign import in the generated Haskell code? If not, that would be a nice feature to add :)

2023-01-17 08:16 UTC, hsyl20 approved these changes
LGTM. I think you should merge your proposed changes. Especially the Haskell/Rust comparison is much better than what I had suggested :)

2023-01-20 14:22 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +#[hs_bindgen]
Not yet! But I will add it to my feature ROADMAP list!

2023-01-20 14:26 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +
After discussing in with @angerman, I think I would remove this part, which isn't really accurate (I save it for another post):

> Furthermore, if you need to share large amounts of data between Rust and Haskell, you may want to consider using [Cap’n Proto](https://capnproto.org/): based on memory sharing, prevents (de)serialization cost by offering a common cross-language custom memory mapping. Each language should use the SDK provided to read/write to it, based on RPC communication primitives, to prevent most of the synchronization issues that comes with shared resources approaches. N.B there is already a [Haskell](https://github.com/zenhack/haskell-capnp) and a [Rust](https://github.com/capnproto/capnproto-rust) implementation!

2023-01-23 08:50 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +At IOG we maintain large Haskell codebases and we would like to interface them with some libraries written in Rust.
```suggestion
At IOG we maintain large [Haskell](https://www.haskell.org) codebases and we would like to interface them with some libraries written in [Rust](https://www.rust-lang.org).
```

2023-01-23 08:51 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +One typical use case concerns cryptographic primitives which must be very performant. The first use case that Iñigo Querejeta Azurmendi (Cardano Lead Cryptography Engineer) brought me consisted in re
```suggestion
One typical use case concerns cryptographic primitives which must be very performant. The first use case that Iñigo Querejeta Azurmendi (Cardano Lead Cryptography Engineer) brought me consisted in replacing a cryptographic library used by [`cardano-base`](https://github.com/input-output-hk/cardano-base). Namely, replacing [`cryptonite`](https://github.com/input-output-hk/cardano-crypto/blob/develop/cbits/cryptonite_sha512.h), a library written in Haskell and C, with [`sha3`](https://crates.io/crates/sha3), a Rust library (or "crate").
```

2023-01-23 08:58 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +> The Rust [ABI](https://doc.rust-lang.org/reference/items/external-blocks.html#abi) (call-convention and types [memory layout](https://cheats.rs/#memory-layout)) isn’t stable [1]. That means that it
```suggestion
> The Rust [ABI](https://doc.rust-lang.org/reference/items/external-blocks.html#abi) (call-convention and types [memory layout](https://cheats.rs/#memory-layout)) isn’t stable. That means that it’s specified internally but could be broken by any `rustc` minor release, building a software on top of it is by definition a “hack” …
```

2023-01-23 09:08 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +> The natural way to do that in Rust, and to have directly access to source code's AST (Abstract Syntax Tree), rather than trying to implement a parser, is to use a macro!
```suggestion
> The natural way to do that in Rust, and to have directly access to source code's AST (Abstract Syntax Tree), rather than trying to implement a parser, is to use a macro!
>
> **To go further:** `c-bindgen` is well known to be buggy! It's a flaw in its design to have a custom Rust source parser, rather using the framework implement here for `hs-bindgen` would allow us to provide a better `c-bindgen` implementation.
```

2023-01-23 09:09 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +* Provided traits implementation for `std` types take care of memory management [2] ;
```suggestion
* Provided traits implementation for `std` types take care of memory management ;
```

2023-01-23 09:10 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +[2] Speaking of memory management, the strategy implemented here is: freeing the value is the role of the receiver (which has “ownership” of it). This means that, e.g. the type that return a Rust fun
```suggestion
**To go further:** speaking of memory management, the strategy implemented here is: freeing the value is the role of the receiver (which has “ownership” of it). This means that, e.g. the type that return a Rust function, will not be [`Drop`](https://doc.rust-lang.org/std/ops/trait.Drop.html) by Rust but rather should be [`free`](https://hackage.haskell.org/package/base/docs/Foreign-Marshal-Alloc.html) on Haskell side!
```

2023-01-23 09:11 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +Thanks for reading, feel free to experiment with this Proof of Concept and to provide feedbacks on GitHub :)
I changed my mind and rather reworked and structure links inside the corpus of the article than dump a big list at the end!

2023-01-23 09:14 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +* Ask user to add `crate-type = ["staticlib"]` (or `"cdylib"`, dynamic libraries require an extra `build.rs` that is generated by `cargo-cabal`) to their `Cargo.toml` ;
```suggestion
* Ask user to add `crate-type = ["staticlib"]` (or `"cdylib"`, dynamic libraries require an extra [`build.rs`](https://github.com/yvan-sraka/cargo-cabal/blob/main/src/build.rs) that is generated by `cargo-cabal`) to their `Cargo.toml` ;
```

2023-01-23 09:15 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +* Generate a custom `X.cabal` linking `rustc` output as `extra-librairies`, and either a ([`naersk`](https://github.com/nix-community/naersk) and [`haskell.nix`](https://github.com/input-output-hk/ha
```suggestion
* Generate a custom `X.cabal` linking `rustc` output as `extra-librairies`, and either a ([`naersk`](https://github.com/nix-community/naersk) and [`haskell.nix`](https://github.com/input-output-hk/haskell.nix) based) `flake.nix` or a [`Setup.lhs`](https://github.com/yvan-sraka/cargo-cabal/blob/main/src/Setup.lhs) build customization (to work around this [issue](https://github.com/haskell/cabal/issues/2641)).
```

2023-01-23 09:16 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +What would be the reason to NOT use `cargo-cabal` and `hs-bindgen`? I should mention that `{-# LANGUAGE CApiFFI #-}` language extonsion features, like using C values that are `#define` in a header or
```suggestion
What would be the reason to NOT use `cargo-cabal` and `hs-bindgen`? I should mention that `{-# LANGUAGE CApiFFI #-}` language extension features, like using C values that are `#define` in a header or `vargs`, are not supported (because they're indeed C specific). E.g. variadic arguments didn't exist in Rust and are usually implemented with [the Builder pattern](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html). Again I want to make obvious that if you're looking for `CApiFFI` features you should embed Rust code in a C library, with e.g. `c-bindgen`, and so not use the tools introduced here!
```

2023-01-23 09:19 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +
```suggestion

**To go further:** there is no first-class `stack` support yet provided, but we could easily imagine a `cargo-stack` binary that just wrap a `cargo-cabal --stack` CLI option!

```

2023-01-23 09:33 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +Finally, It’s worth mentioning that there are also proposals to improve the interface between Haskell programs requiring Rust libraries, including this Cabal [RFC](https://github.com/haskell/cabal/is
```suggestion
Finally, It’s worth mentioning that there are also proposals to improve the interface between Haskell programs requiring Rust libraries, including this Cabal [RFC](https://github.com/haskell/cabal/issues/7906). As a reminder, the implementation proposed here does not provide support for Haskell dependencies in Rust project yet, but there is a previous [unmaintained attempt](https://github.com/mgattozzi/curryrs) of bringing Haskell runtime support in Rust binaries. We should also keep a close look on the Rust RFC that offer to introduce a `#[repr(interop)]` attribute: [Experimental feature gate proposal `interoperable_abi`](https://github.com/rust-lang/rust/pull/105586).
```

2023-01-23 10:19 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +> [FFI](https://doc.rust-lang.org/nomicon/ffi.html) looks like the right choice, it doesn’t rely on any syscall, at runtime they just behave as a jump in memory. Unfortunately, it comes at a cost of
```suggestion
> FFI looks like the right choice, it doesn’t rely on any syscall, at runtime they just behave as a jump in memory. Unfortunately, it comes at a cost of careful special attention on following call-conventions and handling memory management, we will come back to it later!
>
> **To go further:** you can learn more about how to use FFI in Rust by reading the [_The Rustonomicon_](https://doc.rust-lang.org/nomicon/ffi.html) (Unsafe Rust guide) dedicated section, or the dedicated [_Rust FFI Omnibus_](http://jakegoulding.com/rust-ffi-omnibus/) tutorial. The ANSSI (French government security agency) also write about it in [_Secure Rust Guidelines_](https://anssi-fr.github.io/rust-guide/07_ffi.html) guide, and _Rust Embedded_ book have an [Interoperability with C](https://docs.rust-embedded.org/book/interoperability/rust-with-c.html) chapter. On the Haskell side, you way want to take a look at [GHC wiki](https://wiki.haskell.org/GHC/Using_the_FFI) or read the dedicated [_Real-World Haskell_](https://book.realworldhaskell.org/read/interfacing-with-c-the-ffi.html) chapter!
```

2023-01-23 10:27 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +slug: 2023-01-02-hs-bindgen-introduction
```suggestion
slug: 2023-01-23-hs-bindgen-introduction
```

2023-01-23 10:37 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +
```suggestion

I would like to thank [@hsyl20](https://github.com/hsyl20), [@iquerejeta](https://github.com/iquerejeta) and [@govanify](https://github.com/govanify) for their careful reviewing and corrections they provide to make this article in good shape.

```

2023-01-23 16:55 UTC, yvan-sraka commented on blog/2023-01-02-hs-bindgen-introduction.md
> +slug: 2023-01-23-hs-bindgen-introduction
```suggestion
slug: 2023-01-24-hs-bindgen-introduction
```

2023-01-24 09:42 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +slug: 2023-01-23-hs-bindgen-introduction
```suggestion
slug: 2023-01-24-hs-bindgen-introduction
```

2023-01-24 11:00 UTC, hsyl20 requested changes

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> Why not just use, e.g., [Google Protobuf](https://developers.google.com/protocol-buffers) over a [Unix Domain Socket](https://en.wikipedia.org/wiki/Unix_domain_socket)? How to make a choice in this
```suggestion
> As our main criterion is performance, we want a solution with a minimal overhead. In particular we want to avoid the use of any solution that relies on slow IPC (Inter-process communication) and on costly data (de)serialization.
> It leads us to exclude solutions such as, e.g., using [Google Protobuf](https://developers.google.com/protocol-buffers) over a [Unix Domain Socket](https://en.wikipedia.org/wiki/Unix_domain_socket).
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> Binding generation comes to the rescue by considerably reducing the room for human errors, and as a bonus, it simplifies a lot of maintainer job with a more readable reduced codebase.
```suggestion
> Binding generation comes to the rescue by considerably reducing the room for human errors. As a bonus, it also makes maintainers' life easier thanks to a smaller and more readable code base.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +#[no_mangle] // Mangling randomize symbols
```suggestion
#[no_mangle] // Mangling makes symbol names more difficult to predict. We disable it to ensure that the resulting symbol is really `__c_greetings`.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +-- This file was generated by `hs-bindgen` crate and contain C FFI bindings
```suggestion
-- This file was generated by `hs-bindgen` crate and contains C FFI bindings
```

Fix the typo in the generator if it is in there too ;)

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +--   this format has purposely no public specifications).
```suggestion
--   this format has purposely no public specification).
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> So, do not fear the C ABI … because, at least, it is stable!
Also the main argument is probably that GHC doesn't know anything about Rust calling convention, while it does about C's calling convention. C's calling convention is the lingua franca of Rustc/GHC.

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> Binding code generation could have been achieved using an external tool, e.g., `c-bindgen` parses Rust code (before macro expansion) and deduce the right C function signatures.
```suggestion
> Binding code generation could have been achieved using an external tool, e.g., `c-bindgen` parses Rust code (before macro expansion) and deduces the right C function signatures.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> But rather we choose to define a custom macro (like `cxx`, `wasm-bindgen` and `PyO3` does), and so we require the user to depend on a custom crate. Why?
```suggestion
> But instead we decided to define a custom macro (like `cxx`, `wasm-bindgen`, and `PyO3` do), and so we require the user to depend on a custom crate.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> We want generated bindings to always match the source code used for generation, so we want to force the user to integrate binding generation in the build process.
```suggestion
> The reason is that we want generated bindings to always match the source code used for their generation. By using a macro we enforce binding generation during the build process and bindings can't get out-of-sync.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> The natural way to do that in Rust, and to have directly access to source code's AST (Abstract Syntax Tree), rather than trying to implement a parser, is to use a macro!
```suggestion
> In addition macros have direct access to source code's AST (Abstract Syntax Tree) and don't require the use of a parser.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> **To go further:** `c-bindgen` is well known to be buggy! It's a flaw in its design to have a custom Rust source parser, rather using the framework implement here for `hs-bindgen` would allow us to
> `c-bindgen` is well known to be buggy!

[Citation needed]

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +Wrapping user types by these traits have several benefits:
Reintroduce traits here because they were mentioned quite some paragraphs ago. Something like:

```
Traits are the second building block after the `hs-bindgen` macro. They are used to map Rust types to Haskell types (iiuc) as follows...
```

 Perhaps draw an analogy with type-classes so that Haskellers understand what traits are.

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +**To go further:** speaking of memory management, the strategy implemented here is: freeing the value is the role of the receiver (which has “ownership” of it). This means that, e.g. the type that re
```suggestion
**To go further:** the memory management strategy is: freeing the value is the role of the receiver (which has “ownership” of it). This means that values returned by Rust functions aren't [`dropped`](https://doc.rust-lang.org/std/ops/trait.Drop.html) by Rust but rather should be [`freed`](https://hackage.haskell.org/package/base/docs/Foreign-Marshal-Alloc.html) on the Haskell side!

Currently `hs-bindgen` only generates `unsafe` Haskell foreign imports. In the future it could generate `safe` ones too. I invite you to read *[“FFI safety and GC”](https://frasertweedale.github.io/blog-fp/posts/2022-09-23-ffi-safety-and-gc.html)* by Fraser Tweedale or GHC's users guide to understand the differences between `unsafe`/`safe`.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +I was heavily inspired by the developer experience that offers [`wasm-pack`](https://rustwasm.github.io/docs/wasm-pack/) or [`maturin`](https://github.com/PyO3/maturin): launched in any Rust project
```suggestion
I was heavily inspired by the developer experience that offers [`wasm-pack`](https://rustwasm.github.io/docs/wasm-pack/) or [`maturin`](https://github.com/PyO3/maturin): launched in any Rust project folder, these tools help the user to interactively tweak their `Cargo.toml` package file to make sure it is compatible with NPM / PyPI. They even handle the publication of the package on NPM registry and on PyPI package index.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +* Ask user to add `crate-type = ["staticlib"]` (or `"cdylib"`, dynamic libraries require an extra [`build.rs`](https://github.com/yvan-sraka/cargo-cabal/blob/main/src/build.rs) that is generated by `
```suggestion
* Ask the user to add `crate-type = ["staticlib"]` (or `"cdylib"`, dynamic libraries require an extra [`build.rs`](https://github.com/yvan-sraka/cargo-cabal/blob/main/src/build.rs) file that is generated by `cargo-cabal`) to their `Cargo.toml` file;
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +**To go further:** there is no first-class `stack` support yet provided, but we could easily imagine a `cargo-stack` binary that just wrap a `cargo-cabal --stack` CLI option!
```suggestion
**To go further:** `stack` isn't supported yet, but we could easily imagine a `cargo-stack` binary that just wraps a `cargo-cabal --stack` CLI option!
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +* Generate a custom `X.cabal` linking `rustc` output as `extra-librairies`, and either a ([`naersk`](https://github.com/nix-community/naersk) and [`haskell.nix`](https://github.com/input-output-hk/ha
```suggestion
* Generate a custom `X.cabal` linking `rustc` output as `extra-librairies`, and either a ([`naersk`](https://github.com/nix-community/naersk) and [`haskell.nix`](https://github.com/input-output-hk/haskell.nix) based) `flake.nix` or a [`Setup.lhs`](https://github.com/yvan-sraka/cargo-cabal/blob/main/src/Setup.lhs) Cabal build script (to work around this [issue](https://github.com/haskell/cabal/issues/2641)).
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +What would be the reason to NOT use `cargo-cabal` and `hs-bindgen`? I should mention that `{-# LANGUAGE CApiFFI #-}` language extension features, like using C values that are `#define` in a header or
I don't understand this limitation. Haskell also doesn't support varargs. Why would we want to use `CApiFFI` to interact with Rust?

You'd better mention `safe` that is currently unsupported. Or perhaps just remove the section if there is no major drawback to using your solution compared to writing bindings manually.

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +Furthermore, It’s also nice to give a sneak peek on what others do for comparison: **OCaml** [allows extensions to be written directly in Rust with no C stubs](https://docs.rs/ocaml), this work was s
```suggestion
Furthermore, It’s also nice to give a sneak peek on what others do for comparison: **OCaml** [allows extensions to be written directly in Rust with no C stubs](https://docs.rs/ocaml), this work was supported from the [OCaml Software Foundation](http://ocaml-sf.org/) and you can find [a basic example project here](http://github.com/zshipko/ocaml-rust-starter). It offers [safe OCaml/Rust interoperability](https://github.com/simplestaking/ocaml-interop), meaning utilities to convert ADTs (Algebraic Data Types) and functions using them.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +Finally, It’s worth mentioning that there are also proposals to improve the interface between Haskell programs requiring Rust libraries, including this Cabal [RFC](https://github.com/haskell/cabal/is
```suggestion
Finally, it’s worth mentioning that there are also proposals to improve the interface between Haskell programs requiring Rust libraries, including this Cabal [RFC](https://github.com/haskell/cabal/issues/7906). As a reminder, the implementation proposed here does not provide support for Haskell dependencies in Rust project yet, but there is a previous [unmaintained attempt](https://github.com/mgattozzi/curryrs) by Michael Gattozzi of bringing Haskell runtime support in Rust binaries. We should also keep a close look on the Rust RFC that offers to introduce a `#[repr(interop)]` attribute: [Experimental feature gate proposal `interoperable_abi`](https://github.com/rust-lang/rust/pull/105586).
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +I would like to thank [@hsyl20](https://github.com/hsyl20), [@iquerejeta](https://github.com/iquerejeta) and [@govanify](https://github.com/govanify) for their careful reviewing and corrections they
```suggestion
I would like to thank [@hsyl20](https://github.com/hsyl20), [@iquerejeta](https://github.com/iquerejeta) and [@govanify](https://github.com/govanify) for their reviews and for their helpful suggestions.
```

2023-01-24 11:00 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +Thanks for reading, feel free to experiment with this Proof of Concept and to provide feedbacks on GitHub :)
```suggestion
Thanks for reading, feel free to experiment with this Proof of Concept and to provide feedback on GitHub!
```

2023-01-24 11:36 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +/// `hs-bindgen = { ..., features = [ "full" ] }`
It actually depends on how `hs-bindgen` is installed in four crate:
```shell
cargo add hs-bindgen
# VS
cargo add hs-bindgen --features full
```
And yes, I choose to disable this feature by default because inferring signature requires a hack that I prefer to keep optional. The code would look like that if we rather explicitly declare wanted Haskell signature:
```rust
use hs_bindgen::*;

#[hs_bindgen(CString -> IO ())]
 fn greetings(name: &str) {
     println!("Hello, {name}!");
 }
 ```
I guess I could rather use this piece of code in my article, so I keep it simple, and I don't advertise a feature that I on purpose decide to be opt-out by default!

2023-01-24 11:46 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> So, do not fear the C ABI … because, at least, it is stable!
That's sure! But I mean even with a big GHC development effort to support Rust calling convention, we have to be aware that `rustc` calling convention isn't a public API on which we could build things on top … Since version 1.0.0 of the language, `rustc` core team pushed several calling convention break non-retro-compatible changes … We have to consider that linking 2 rust binaries built with different minor `rustc` version is `unsafe` …

2023-01-24 11:51 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> The natural way to do that in Rust, and to have directly access to source code's AST (Abstract Syntax Tree), rather than trying to implement a parser, is to use a macro!
I think my phrasing is a bit incorrect here, since Rust procedural or attribute macro take as input a `TokenStream` rather than a structured AST, there is still parsing to do (that what the `syn` crate does). Maybe this is details of implementation, my point is more “there will still be parsing, but we do not implement a custom parser”.

2023-01-24 11:53 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> So, do not fear the C ABI … because, at least, it is stable!
https://blaz.is/blog/post/we-dont-need-a-stable-abi/ mention it, but I do not know if it's a valuable source of truth.

2023-01-24 11:54 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> **To go further:** `c-bindgen` is well known to be buggy! It's a flaw in its design to have a custom Rust source parser, rather using the framework implement here for `hs-bindgen` would allow us to
https://blaz.is/blog/post/we-dont-need-a-stable-abi/ mention it, but I do not know if it's a valuable source of truth.

2023-01-24 12:06 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +What would be the reason to NOT use `cargo-cabal` and `hs-bindgen`? I should mention that `{-# LANGUAGE CApiFFI #-}` language extension features, like using C values that are `#define` in a header or
Yes, you're right. I will just remove this section for now. Maybe come back to it in a follow-up article!

2023-01-24 12:48 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +/// `hs-bindgen = { ..., features = [ "full" ] }`
Ah yes that would be better, otherwise anyone trying to reproduce your example will wonder why it doesn't work.

Keep the type inference feature for a future blog post perhaps :)

2023-01-24 12:50 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> The natural way to do that in Rust, and to have directly access to source code's AST (Abstract Syntax Tree), rather than trying to implement a parser, is to use a macro!
I struggled to reformulate this. Perhaps that it goes without saying it explicitly and you could just remove this sentence?

2023-01-24 12:52 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> **To go further:** `c-bindgen` is well known to be buggy! It's a flaw in its design to have a custom Rust source parser, rather using the framework implement here for `hs-bindgen` would allow us to
Perhaps soften the wording then. Just mention that `c-bindgen` could reuse `hs-bindgen` implementation instead of rolling out his own Rust source parser.

2023-01-24 12:53 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +I was heavily inspired by the developer experience that offers [`wasm-pack`](https://rustwasm.github.io/docs/wasm-pack/) or [`maturin`](https://github.com/PyO3/maturin): launched in any Rust project
I know next to nothing about these tools, and it shows :)

2023-01-25 08:28 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> So, do not fear the C ABI … because, at least, it is stable!
I reworked the paragraph, integrating your main argument for clarity :)

2023-01-25 09:01 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +Wrapping user types by these traits have several benefits:
I added a little paragraph :)

2023-01-25 09:02 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> **To go further:** `c-bindgen` is well known to be buggy! It's a flaw in its design to have a custom Rust source parser, rather using the framework implement here for `hs-bindgen` would allow us to
I reformulate it :)

2023-01-25 09:03 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +I was heavily inspired by the developer experience that offers [`wasm-pack`](https://rustwasm.github.io/docs/wasm-pack/) or [`maturin`](https://github.com/PyO3/maturin): launched in any Rust project
I apply your corrections, reformulate it and remove the last sentence :)

2023-01-25 09:03 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> The natural way to do that in Rust, and to have directly access to source code's AST (Abstract Syntax Tree), rather than trying to implement a parser, is to use a macro!
I just removed this sentence!

2023-01-25 09:11 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> FFI looks like the right choice, it doesn’t rely on any syscall, at runtime they just behave as a jump in memory. Unfortunately, it comes at a cost of careful special attention on following call-co
To me, it's a bit weird to call `FFI` an `IPC`, since it will share the same process (or at least the same memory addresses space).

2023-01-25 09:15 UTC, yvan-sraka commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> Why not just use, e.g., [Google Protobuf](https://developers.google.com/protocol-buffers) over a [Unix Domain Socket](https://en.wikipedia.org/wiki/Unix_domain_socket)? How to make a choice in this
I think this is important to remind that relying on any syscall (like I/O) will be a major performance bottleneck. So, I'm not sure about the distinction between slow VS fast IPC protocols?

2023-01-25 09:32 UTC, hsyl20 commented on blog/2023-01-24-hs-bindgen-introduction.md
> +> FFI looks like the right choice, it doesn’t rely on any syscall, at runtime they just behave as a jump in memory. Unfortunately, it comes at a cost of careful special attention on following call-co
Ah yes, you could replace "IPC" with something like "communication channel" perhaps?

I've introduced IPC because you mentioned that you wouldn't select Google protobuf for two reasons (basically slow communication channel (because Unix domain socket -> syscall -> slow), and data (de)serialization).

For FFI the "communication channel" is shared memory and there is almost no data (de)serialization (just massaging of values using traits iiuc).

---

Alternatively you could drop every mention of IPC/"communication channel" entirely, including mentions of Unix Socket Domain. Just mention that data serialization must be the most efficient, so no Google protobuf, no yaml, etc.

2023-01-25 17:26 UTC, doyougnu requested changes
Some minor fixes that sounded strange to me as a native English speaker. All in all it was good!

2023-01-25 17:26 UTC, doyougnu commented on blog/2023-01-25-hs-bindgen-introduction.md
> +[`cargo-cabal`](https://github.com/yvan-sraka/cargo-cabal) is a CLI tool that helps you, in one simple command, turning a Rust crate into a Haskell Cabal library!
```suggestion
[`cargo-cabal`](https://github.com/yvan-sraka/cargo-cabal) is a CLI tool that helps you, in one simple command, turn a Rust crate into a Haskell Cabal library!
```

2023-01-25 17:26 UTC, doyougnu commented on blog/2023-01-25-hs-bindgen-introduction.md
> +I was heavily inspired by the developer experience that offers [`wasm-pack`](https://rustwasm.github.io/docs/wasm-pack/) or [`maturin`](https://github.com/PyO3/maturin): launched in any Rust project
```suggestion
I was heavily inspired by the developer experience that offers [`wasm-pack`](https://rustwasm.github.io/docs/wasm-pack/) or [`maturin`](https://github.com/PyO3/maturin): launched in any Rust project folder. These tools help the user interactively tweak their `Cargo.toml` package file and generate the build files needed by Node.js `npm` or Python `setuptools`.
```

2023-01-25 17:26 UTC, doyougnu commented on blog/2023-01-25-hs-bindgen-introduction.md
> +[`cargo-cabal`](https://github.com/yvan-sraka/cargo-cabal) and [`hs-bindgen`](https://github.com/yvan-sraka/hs-bindgen) combined are less than 1000 LoC, they also support Rust `#[no_std]` code, and I
```suggestion
[`cargo-cabal`](https://github.com/yvan-sraka/cargo-cabal) and [`hs-bindgen`](https://github.com/yvan-sraka/hs-bindgen) combined are less than 1000 LoC, they also support Rust `#[no_std]` code, and I would be glad to keep them as [KISS](https://en.wikipedia.org/wiki/KISS_principle) and modular as possible. But there is still room for improvements, e.g., by adding trait implementations for more Rust `std` types, or possibly supporting `async` functions with [`async-ffi`](https://github.com/oxalica/async-ffi)?!
```

2023-01-25 17:26 UTC, doyougnu commented on blog/2023-01-25-hs-bindgen-introduction.md
> +It would be delightful to get as far as having custom preludes in Haskell binding code generated that offers Rust type layout in Haskell. E.g. Rust [slices](https://doc.rust-lang.org/book/ch04-03-sli
```suggestion
It would be delightful to get as far as having custom preludes in Haskell binding code, that offers Rust type layout in Haskell. For example, Rust [slices](https://doc.rust-lang.org/book/ch04-03-slices.html) are not an existing concept in C but could be easily represented as an FFI-safe struct.
```

2023-01-25 17:26 UTC, doyougnu commented on blog/2023-01-25-hs-bindgen-introduction.md
> +Finally, it’s worth mentioning that there are also proposals to improve the interface between Haskell programs requiring Rust libraries, including this Cabal [RFC](https://github.com/haskell/cabal/is
```suggestion
Finally, it’s worth mentioning that there are also proposals to improve the interface between Haskell programs requiring Rust libraries, including this Cabal [RFC](https://github.com/haskell/cabal/issues/7906). As a reminder, the implementation proposed here does not provide support for Haskell dependencies in Rust project yet, but there is a previous [unmaintained attempt](https://github.com/mgattozzi/curryrs) by Michael Gattozzi to bring Haskell runtime support to Rust binaries. We should also keep a close look on the Rust RFC that offers to introduce a `#[repr(interop)]` attribute: [Experimental feature gate proposal `interoperable_abi`](https://github.com/rust-lang/rust/pull/105586).
```

2023-01-25 17:26 UTC, doyougnu commented on blog/2023-01-25-hs-bindgen-introduction.md
> +I would like to thank [@hsyl20](https://github.com/hsyl20), [@iquerejeta](https://github.com/iquerejeta) and [@govanify](https://github.com/govanify) for their reviews and for their helpful suggestio
```suggestion
I would like to thank [@hsyl20](https://github.com/hsyl20), [@iquerejeta](https://github.com/iquerejeta), [@govanify](https://github.com/govanify), and [@doyougnu](https://github.com/doyougnu) for their reviews and for their helpful suggestions.
```

2023-01-25 17:26 UTC, doyougnu commented on blog/2023-01-25-hs-bindgen-introduction.md
> +Thanks for reading, feel free to experiment with this Proof of Concept and to provide feedback on GitHub!
```suggestion
Thanks for reading, feel free to experiment with this proof of concept and to provide feedback on GitHub!
```

2023-01-26 09:35 UTC, merged