WIP blog post & associated example code for GHC JS browser example
input-output-hk/engineering pull request #24
Opened 2022-12-19 05:00 UTC by JoshMeredith

2022-12-19 16:09 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +## Introduction
Could you start where we left in the previous blog post:
1. installing the JS backend
2. build and running an HelloWorld.hs
3. Transition. Something like "Except for portability, compiling Haskell programs into JavaScript code that can be run with NodeJS isn't very useful in comparison to compiling them to native machine code. Let's build a more compelling example where JavaScript is mandatory: a Web Application."
4. Introduction to the Web Application you plan to implement in the tutorial

2022-12-19 16:12 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +On the JavaScript side (in `js/example.js`), we have:
You don't need to use a foreign `.js` file. You can write the function inline:

```
foreign import javascript
  "((buf,offset) => {\
  \ document.body.innerHTML = \"example\" + h$decodeUtf8z(buf,offset);\
  \ })"
  setInnerHtml :: CString -> IO ()
```

2022-12-19 16:14 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +- _TODO: Explain unsafe vs interruptible_
No don't explain this. It's a tutorial, don't add explanations (cf https://diataxis.fr/tutorials/).

2022-12-19 16:20 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +## Current Limitations
To avoid the current limitations (cabal, bytestring), you can build a simple example that generates a SVG by hand first (e.g. a circle).

2022-12-22 12:47 UTC, hsyl20 reviewed
It looks good, thanks Josh!

2022-12-22 12:47 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +Take note of this `_build/stage1/bin/js-unknown-ghcjs-ghc` path, as it's the GHC executable that we'll be using to compile to JavaScript.
Perhaps define an alias here:

```
alias ghc-js=`pwd`/_build/stage1/bin/js-unknown-ghcjs-ghc
```

And use it later to make the command-line nicer

2022-12-22 12:47 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +We saw in the previous example that the GHC's JavaScript backend allows us to write Haskell to run with NodeJS. This produces a portable executable, but otherwise doesn't enable anything we couldn't
```suggestion
We saw in the previous example that the GHC's JavaScript backend allows us to write Haskell to run with NodeJS. This produces a portable executable, but otherwise doesn't enable anything we couldn't do before - GHC can already compile Haskell to run on most platforms! So, we'll present a unique possibility: running Haskell in the browser.
```

2022-12-22 12:47 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +foreign import javascript unsafe "((html) => document.body.innerHTML = h$decodeUtf8z(html,0))"
```suggestion
foreign import javascript "((html) => document.body.innerHTML = h$decodeUtf8z(html,0))"
```

I don't think `unsafe` is needed. Avoiding it avoids having to explain it :)

2022-12-22 12:47 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +main = setInnerHtml =<< newCString circle
```suggestion
main = withCString circle setInnerHtml
```

To properly release the CString

2022-12-22 12:47 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +TODO: Teaser on next post?
Yes! We should also mention somehow that:

1. Documentation in general and especially about the FFI is lacking (e.g .in the user guide)
2. Foreign exports aren't supported

Something like:

> This is the first tutorial in a series about the JavaScript backend. We plan to write more of those in the coming weeks and months as we add new features (e.g. support for "foreign exports" that will allow JavaScript code to call into Haskell code, support for Template Haskell, etc.). For now it relies on our "insider" knowledge (e.g. how the FFI works) that isn't well documented elsewhere. We do plan to add a chapter about the JavaScript backend in GHC's user guide, but for now your best chance is to look at GHCJS's documentation or at the source code.

2023-01-06 14:35 UTC, doyougnu reviewed
just a few minor things, no big restructuring! Good Job!

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +In the last post we introduced GHC's new JavaScript backend, which allows the compilation of Haskell code into JavaScript. Because of the prevalence of JavaScript, this opens up the ability for Haske
Good intro! Use an active voice:

```suggestion
In the last post we introduced GHC's new JavaScript backend, which allows the compilation of Haskell code into JavaScript. Because of the prevalence of JavaScript, this opens up the ability for Haskell to be used on new platforms - particularly the browser. In this post, we'll look build a version of GHC that will compile to JavaScript, and use that to run a Haskell program in a browser. 
```

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +### Installing Dependencies
Structure this better, perhaps like this:

- First we need these dependencies to build GHC from source:
- then list out the dependencies
- Then describe where and how to get them in the exact same order  as the list

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +After installing Emscripten, `emconfigure` should be available on your system path. For more detailed installation instructions, see [https://emscripten.org/docs/getting_started/downloads.html](https
provide a way to check that its on the path (untested):

```
echo $PATH | grep emconfigure
```

then link to the docs

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +If everything is correct, you'll see that the `Target platform` is set to `js-unknown-ghcjs`.
```suggestion
If everything is correct, you'll see that the `Target platform` is set to `js-unknown-ghcjs` and the tools needed to build set to their Emscripten counterparts, e.g., `ar` becomes `emar`, `nm` becomes `llvm-nm` etc.
```

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +If everything is correct, you'll see that the `Target platform` is set to `js-unknown-ghcjs`.
Also this section does everything it needs to and is clear and concise, good job!

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +./hadrian/build --bignum=native -j
```suggestion
./hadrian/build --bignum=native -j --docs=none
```

no need to build docs

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +Which will result in:
```suggestion
Expect this to take around a half hour or longer. If all goes well you should see:
```

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +Now that we have a version of GHC that can output JavaScript, let's move on to using it to compile a Haskell program, which we can run using NodeJS. Make a file named "HelloJS.hs", with the following
more active voice:

```suggestion
Now that we have a version of GHC that can output JavaScript, let's compile a Haskell program which we can run using NodeJS. Make a file named "HelloJS.hs", with the following contents:
```

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +Then, to compile it to JavaScript, we'll need the path to the new GHC executable we just built. To run it, use:
simplify a bit:

```suggestion
Now  it compile using the GHC executable we just built:
```

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +You'll also notice that a folder called `HelloJS.jsexe` is produced. It has all of our final JavaScript code in it, including a file named `all.js`. The above executable is just a copy of `all.js`, w
```suggestion
Notice that a folder called `HelloJS.jsexe` was produced. This directory has all the final JavaScript code in it, including a file named `all.js`.  `all.js` _is_ the payload our our hello world executable. The executable is simply a copy of `all.js` with a call to `node` added to the top. So, we can also run our program with:
```

Just a bit of reformatting. The writing principle here is that sentences should be transitive. So if you have two sentences `A : a -> b` and `B: b -> c` then writing `A. B` is better than having `B': c -> b` and writing `A. B'`. In the referenced text you end up with a `B'` because you have the first sentence that is `HelloJS.jsexe -> all.js`, and then the next sentence is `above executable -> all.js -> node`. I'm just tracking the subjects of the sentences here. So the fix is to move `all.js` to be the first subject of the second sentence which means it immediately follows from the last subject of the first sentence.

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +main = withCStraing circle setInnerHtml
`main = withCStraing circle setInnerHtml`

is `withCStraing` a typo?

shouldn't it be `withCString`?

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +main = withCStraing circle setInnerHtml
also I wonder if we can get docusaurus to run these examples in the future

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +Now, inside the HelloBrowser.jsexe folder, there will be an `index.html` file. This HTML file has our compiled JavaScript already included, so if you open it in your browser, you'll find it loads our
You should introduce the `index.html` file when you introduce the `.jsexe` folder. Just something small:

> Notice the all.js and index.html files, for now we'll only care about `all.js` and return to `index.html` later

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +Now, inside the HelloBrowser.jsexe folder, there will be an `index.html` file. This HTML file has our compiled JavaScript already included, so if you open it in your browser, you'll find it loads our
You should show loading the index file into the browser:

```
$ firefox <path-to-index.html>
```
or
```
$ google-chrome-stable <path-to-index.html>
```
or
```
$ chromium ...
```

you get the idea

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +Now, inside the HelloBrowser.jsexe folder, there will be an `index.html` file. This HTML file has our compiled JavaScript already included, so if you open it in your browser, you'll find it loads our
then take a snapshot and include that in the post

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +main = withCStraing circle setInnerHtml
also also you need to explain this code!

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +In this example we've encountered a Haskell feature that's only available in the JavaScript backend - JavaScript foreign imports. This feature allows us to write JavaScript arrow functions for use in
move this to right after the code above, and drop the `in this example`. That was just for summary.

2023-01-06 14:35 UTC, doyougnu commented on blog/ghc-js-browser-example/browser-example.md
> +In this example we've encountered a Haskell feature that's only available in the JavaScript backend - JavaScript foreign imports. This feature allows us to write JavaScript arrow functions for use in
```suggestion
In this example we've encountered a Haskell feature that's only available in the JavaScript backend - JavaScript foreign imports. This feature allows us to write JavaScript [arrow functions](https://262.ecma-international.org/13.0/#prod-ArrowFunction) for use in our Haskell program. Here, it's allowed us to write a function to access the `body` of the HTML, and replace its contents with our SVG string.
```

2023-01-06 14:37 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +In the last post we introduced GHC's new JavaScript backend, which allows the compilation of Haskell code into JavaScript. Because of the prevalence of JavaScript, this opens up the ability for Haske
Replace `In the last post` with a link to the post.

2023-01-10 14:26 UTC, hsyl20 commented
As discussed in the GHC call, we should probably document clearly that the JS backend isn't feature complete yet to lower expectations (mentioning missing TH, etc.).

2023-01-10 14:34 UTC, JoshMeredith commented
> As discussed in the GHC call, we should probably document clearly that the JS backend isn't feature complete yet to lower expectations (mentioning missing TH, etc.).

Is this appropriate for the conclusion section?

2023-01-10 15:04 UTC, hsyl20 commented
> > As discussed in the GHC call, we should probably document clearly that the JS backend isn't feature complete yet to lower expectations (mentioning missing TH, etc.).
> 
> Is this appropriate for the conclusion section?

At the end of the introduction perhaps to be sure that most people read it?

2023-01-16 10:54 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +This is the first tutorial in a series about the JavaScript backend. We plan to write more of these in the coming weeks and months as we add new features (e.g. support for "foreign exports" that will
This text is duplicated in the intro

2023-01-16 15:01 UTC, Swordlash commented
Hey, is this possible to also add a small example of passing Haskell callback into foreign code? Something along the lines of
```
setOnBodyClick :: IO () -> IO ()
setOnBodyClick callback = ... some function calling document.body.onclick = (() => callback ())
```
(is it possible yet in the alpha?)

2023-01-16 15:17 UTC, hsyl20 commented
> Hey, is this possible to also add a small example of passing Haskell callback into foreign code? Something along the lines of
> 
> ```
> setOnBodyClick :: IO () -> IO ()
> setOnBodyClick callback = ... some function calling document.body.onclick = (() => callback ())
> ```
> 
> (is it possible yet in the alpha?)

Hey, I was planning to answer your original comments about this (https://discourse.haskell.org/t/ghc-js-backend-calling-haskell-callback-in-a-foreign-function/5591) :)

I don't think this is supported yet. We've only ported basic foreign imports, not foreign exports nor magical foreign imports (`wrapper`, etc.).

2023-01-16 15:44 UTC, Swordlash commented
Oh sorry, I thought you may have not seen it. Sorry then for polluting the PR.

2023-01-16 16:28 UTC, hsyl20 commented
> Oh sorry, I thought you may have not seen it. Sorry then for polluting the PR.

No problem! Thanks for trying the backend and for the budge! :-) We'll try to prioritize foreign exports and to publish a blog post about them as soon as they are supported.

2023-01-18 08:42 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +After installing Emscripten, `emconfigure` should be available on your system path. For more detailed installation instructions, see [https://emscripten.org/docs/getting_started/downloads.html](https
Used `which emconfigure`

2023-01-18 08:53 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +This is the first tutorial in a series about the JavaScript backend. We plan to write more of these in the coming weeks and months as we add new features (e.g. support for "foreign exports" that will
Rewrote the conclusion version.

2023-01-18 09:10 UTC, hsyl20 requested changes
I've left a few more comments.

Some of @doyougnu's comments don't appear anymore in the "changes" view afaict. For example I remember him asking for a screenshot of the result. That would be nice to have. I've re-added a comment about this.

Also the path of the md file isn't correct: it must be directly in the `blog` directly for it to be found by the blog engine (I think).

2023-01-18 09:10 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +`js-sources` in a `.cabal` file (the `h$` is just convention).
`js-sources` doesn't work with stock Cabal (cf https://github.com/haskell/cabal/pull/8636). Let's not propose to try this.

```suggestion
where `setInnerHTML` is a function defined in a `.js` file that you can pass on GHC's command line.
```

2023-01-18 09:10 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +
```suggestion
Or `ghc-js HelloBrowser.hs foo.js` if `setInnerHTML` is defined in `foo.js`
```

2023-01-18 09:10 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +Now, inside the HelloBrowser.jsexe folder, there will be an `index.html` file.
```suggestion
Now, inside the `HelloBrowser.jsexe` directory there will be an `index.html` file.
```

2023-01-18 09:10 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +
A screenshot would be nice.

2023-01-18 09:10 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +
We must mention that currently "foreign exports" and "wrapper" foreign imports aren't supported and that it drastically limits what one can do. In particular the JS code can't call into the Haskell code yet. This is a severe limitation that should be removed soon as we implement these missing features.

2023-01-18 10:12 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +
Slug added in latest version.

2023-01-18 10:12 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +[post](https://engineering.iog.io/2022-12-13-ghc-js-backend-merged) we
Changed to "In the previous"

2023-01-18 10:13 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +That's all we need to build GHC as a cross compiler. NodeJS can be installed via your system's package manager if you want to run the JavaScript programs locally. We'll assume its in your `$PATH` for
Fixed. Thanks for the proofread!

2023-01-18 10:13 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +If you have NodeJS installed, this executable can be run just like any other command line program, which will output `Hello, JavaScript` to the console:
Fixed!

2023-01-18 10:14 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +Notice that a folder called `HelloJS.jsexe` was produced. This directory contains all the final JavaScript code in it, including a file named `all.js`, and a minimal `index.html` HTML file that wraps
Included these changes.

2023-01-18 10:16 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +`js-sources` in a `.cabal` file (the `h$` is just convention).
Made a similar change in the latest version.

2023-01-18 10:16 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +
Added

2023-01-18 10:16 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +Now, inside the HelloBrowser.jsexe folder, there will be an `index.html` file.
Fixed

2023-01-18 10:18 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +
Added with the markdown image syntax `![Example webpage screenshot](browser-screenshot.png)` and the image file in `engineering/static/img`. I'm not sure if this is correct for the blog engine.

2023-01-18 10:21 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +
Here's the current wording which I think should serve the combined warning/invite to future posts
```
This is the first tutorial in a series about the JavaScript backend, which is currently under active deveopment. Not all Haskell features are supported as of yet. Importantly, there is no current way for JavaScript code to call into Haskell code ("Foreign Exports"), which is a heavy limitation. Template Haskell and "wrapper" foreign imports are also unsupported. As development progresses and the backend gains support for these features, we will be writing more tutorials to introduce them!
```

2023-01-19 12:00 UTC, hsyl20 requested changes

2023-01-19 12:00 UTC, hsyl20 commented on blog/2023-01-18-javascript-browser-tutorial.md
> +title: JavaScript backend merged into GHC
Wrong title

2023-01-19 12:00 UTC, hsyl20 commented on blog/2023-01-18-javascript-browser-tutorial.md
> +authors: [sylvain, doyougnu, luite, josh, moritz]
```suggestion
authors: [sylvain, doyougnu, luite, josh]
```

2023-01-19 12:00 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +[post](https://engineering.iog.io/2022-12-13-ghc-js-backend-merged) we
Well there has been another post in between (https://engineering.iog.io/2023-01-12-ghc-update), so `in a previous` seems better than `in the previous` to me.

2023-01-19 12:00 UTC, hsyl20 commented on blog/2023-01-18-javascript-browser-tutorial.md
> +
Here we should add a warning about the JS backend being a technology preview to lower expectations (cf discussions with David, GHC HQ, etc.)

2023-01-19 12:31 UTC, JoshMeredith commented on blog/2023-01-18-javascript-browser-tutorial.md
> +title: JavaScript backend merged into GHC
Fixed to `Using GHC's JavaScript Backend in the Browser`

2023-01-19 12:34 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +[post](https://engineering.iog.io/2022-12-13-ghc-js-backend-merged) we
fixed

2023-01-19 12:41 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +We saw in the previous example that the GHC's JavaScript backend allows us to write Haskell to run with NodeJS. This produces a portable executable, but otherwise doesn't enable anything we couldn't
fixed

2023-01-19 12:42 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +In this example we've encountered a Haskell feature that's only available in the JavaScript backend - JavaScript foreign imports. This feature allows us to write JavaScript [arrow functions](https://
Used these changes.

2023-01-19 12:42 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +foreign import javascript "h$setInnerHTML"
fixed

2023-01-19 12:47 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +foreign import javascript "((html) => document.body.innerHTML = h$decodeUtf8z(html,0))"
When would we want to use the offset parameter? IMO, this would distract from the example because it draws focus to the internal library.

2023-01-19 13:25 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +foreign import javascript "((html) => document.body.innerHTML = h$decodeUtf8z(html,0))"
A Addr# is represented by two JS values: an array object and an offset number. Using only one isn't correct. If the offset isn't 0 then the code you have isn't correct.

Even if it works in this case, we would have a harder time explaining later that Addr# is represented by two values if the first example we gave was wrong.

2023-01-19 13:52 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +foreign import javascript "((html) => document.body.innerHTML = h$decodeUtf8z(html,0))"
Is there a way to determine the offset given the newly formed `CString` passed to us by `withCString`?

2023-01-19 14:40 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +foreign import javascript "((html) => document.body.innerHTML = h$decodeUtf8z(html,0))"
Yes, that's the second argument that is passed...

An Haskell `CString` is a `Ptr CChar`, hence ultimately an `Addr#`. `Addr#` are represented with 2 JS values: an array and an offset. That's why we define a function that takes two arguments on the JS side, while we only pass one on the Haskell side. In the call earlier today we've been discussing this, especially that `Addr#` could have a `Tuple [AddrRep, IntRep]` kind in JS to more accurately reflect this.

2023-01-19 14:46 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +foreign import javascript "((html) => document.body.innerHTML = h$decodeUtf8z(html,0))"
Ok I see, that does seem to work. I thought there would be extra we'd have to pass from the Haskell side. It seems weird to me that it partially worked if the previous `html` variable covered this tuple. In that case I'm not sure why `h$decodeUtf8z((arr,offset),0)` didn't error. I guess I'll just have to assume that's a JavaScript oddity?

2023-01-19 14:48 UTC, JoshMeredith commented on blog/ghc-js-browser-example/browser-example.md
> +foreign import javascript "((html) => document.body.innerHTML = h$decodeUtf8z(html,0))"
changes made

2023-01-19 14:51 UTC, hsyl20 commented on blog/ghc-js-browser-example/browser-example.md
> +foreign import javascript "((html) => document.body.innerHTML = h$decodeUtf8z(html,0))"
No the previous `html` variable didn't contain a tuple, only the first argument (the array). The second argument (the offset) was silently dropped because it's JavaScript and the caller can pass fewer or too many arguments without a warning:

```js
> let foo = (a,b) => console.log("a: " + a + ", b: " + b)
> foo(10)
a: 10, b: undefined
> foo(10,12)
a: 10, b: 12
> foo(10,12,14)
a: 10, b: 12
```

2023-01-19 15:18 UTC, doyougnu commented
> Also the path of the md file isn't correct: it must be directly in the `blog` directly for it to be found by the blog engine (I think).

I don't think we have a static asset folder defined in `docusaurus.config.js`, see the docs: https://docusaurus.io/docs/markdown-features/assets#static-assets

2023-01-19 16:11 UTC, JoshMeredith commented
> > Also the path of the md file isn't correct: it must be directly in the `blog` directly for it to be found by the blog engine (I think).
> 
> I don't think we have a static asset folder defined in `docusaurus.config.js`, see the docs: https://docusaurus.io/docs/markdown-features/assets#static-assets
> 
> and I bet that's why docusaurus looks at `blog`, it must use the directory of the post as default or last-to-try

Thanks for finding the setting! Hopefully it’s enough that I’ve added that now.

2023-01-20 01:54 UTC, doyougnu commented
just pushed a bunch of fixes. The conclusion needs to be fixed to not repeat (almost verbatim) the introduction. The conclusion should recite the entire post, but inside out (that is, started from the last thing in the post and work its way back to the introduction). 

Other than that LGTM!

2023-01-20 04:59 UTC, JoshMeredith commented
Added a conclusion rewording

2023-01-20 12:24 UTC, hsyl20 commented on blog/2023-01-18-javascript-browser-tutorial.md
> +Recall the `index.html` file inside the HelloBrowser.jsexe directory. This HTML
```suggestion
Recall the `index.html` file inside the `HelloBrowser.jsexe` directory. This HTML
```

2023-01-20 12:33 UTC, hsyl20 commented on blog/2023-01-18-javascript-browser-tutorial.md
> +It's also possible to use our program with existing HTML. In `index.html`, you'll find the line:
```suggestion
`index.html` contains the minimal HTML code required to load the generated JavaScript code. It simply loads the `all.js` file mentioned above with the following `script` tag that you can reuse in your own HTML files:
```

2023-01-20 12:41 UTC, hsyl20 commented on blog/2023-01-18-javascript-browser-tutorial.md
> +This references the `all.js` file that we described in the first example. So, if we had a HTML document with content, and we wanted to modify it via Haskell, we'd just have to include our program wit
```suggestion

As the JS backend still lacks support for some FFI features (foreign exports, foreign "wrapper" imports...), JavaScript codes can't easily interact with Haskell codes. It reduces the amount of advanced/interesting examples we can present for now. We'll publish new blog posts illustrating these features when they will be implemented.
```

2023-01-20 12:42 UTC, hsyl20 approved these changes

2023-01-20 12:42 UTC, hsyl20 commented
I've added a few changes. LGTM

2023-01-21 07:58 UTC, luite commented on blog/2023-01-18-javascript-browser-tutorial.md
> +currently not possible for JavaScript code to call into Haskell code ("foreign
I'd say that it's rather complicated, rather than impossible (you can create callbacks and hand them over to JS. This is how `mkTx` worked, a small `main` that just creates all callbacks for the library to build the library API)

2023-01-21 07:59 UTC, luite commented on blog/2023-01-18-javascript-browser-tutorial.md
> +* (Optional) NodeJS to run JavaScript locally
Emscripten comes with nodejs and adds it to the `PATH` when running `emsdk_env.sh`

2023-01-21 08:00 UTC, luite commented on blog/2023-01-18-javascript-browser-tutorial.md
> +/path/to/emsdk/upstream/escripten/emconfigure
typo, `escripten` -> `emscripten`

2023-01-21 08:01 UTC, luite commented on blog/2023-01-18-javascript-browser-tutorial.md
> +That's all we need to build GHC as a cross compiler. NodeJS can be installed via your system's package manager if you want to run the JavaScript programs locally. We'll assume it's in your `$PATH` fo
Should already be in `$PATH` after running `emsdk_env.sh`

2023-01-21 08:09 UTC, luite commented on blog/2023-01-18-javascript-browser-tutorial.md
> +As the JS backend still lacks support for some FFI features (foreign exports, foreign "wrapper" imports...), JavaScript codes can't easily interact with Haskell codes. It reduces the amount of advanc
Not sure if the `createCallback` API has been merged, if it's the case then we might link to it for people who are a bit more adventurous. Now it looks like it's more limited than it actually is.

2023-01-23 03:48 UTC, JoshMeredith commented on blog/2023-01-18-javascript-browser-tutorial.md
> +/path/to/emsdk/upstream/escripten/emconfigure
typo fixed

2023-01-23 03:58 UTC, JoshMeredith commented on blog/2023-01-18-javascript-browser-tutorial.md
> +currently not possible for JavaScript code to call into Haskell code ("foreign
I think calling it impossible is consistent with the messaging that it's a technology preview, even if there's technically a work-around.

Could we get @hsyl20 and @doyougnu's thoughts on this?

2023-01-23 04:00 UTC, JoshMeredith commented on blog/2023-01-18-javascript-browser-tutorial.md
> +* (Optional) NodeJS to run JavaScript locally
IMO it's better to decouple the node installation here. It allows us to mention why it's needed, and lets it be used from a secondary terminal that hasn't `source`d `emsdk_env.sh`.

2023-01-24 09:18 UTC, hsyl20 commented on blog/2023-01-18-javascript-browser-tutorial.md
> +As the JS backend still lacks support for some FFI features (foreign exports, foreign "wrapper" imports...), JavaScript codes can't easily interact with Haskell codes. It reduces the amount of advanc
I don't know either. Let's keep this for a future blog post IMHO

2023-01-24 09:18 UTC, hsyl20 commented on blog/2023-01-18-javascript-browser-tutorial.md
> +currently not possible for JavaScript code to call into Haskell code ("foreign
```suggestion
currently rather complicated for JavaScript code to call into Haskell code ("foreign
```

2023-01-24 09:18 UTC, hsyl20 commented on blog/2023-01-18-javascript-browser-tutorial.md
> +currently not possible for JavaScript code to call into Haskell code ("foreign
We can soften the wording though even if we don't explain more.

2023-01-24 09:31 UTC, merged