blog: add luite blog for ghcjs/iserv
input-output-hk/engineering pull request #5
Opened 2022-05-17 07:02 UTC by luite

may blog post for (initial) ghcjs/iserv report.

2022-05-17 08:38 UTC, hsyl20 approved these changes
Thanks!

2022-05-17 08:38 UTC, hsyl20 commented on blog/2022-05-17-javascript-template-haskell-ext-interp.md
> +The biggest change is that we have to rework the linker: `thrunner` does not contain any linking logic by itself: GHCJS compiles everything to JavaScript and sends compiled code to the `thrunner` pro
```suggestion
The biggest change is that we have to rework the linker: `thrunner` does not contain any linking logic by itself: GHCJS compiles everything to JavaScript and sends compiled code to the `thrunner` process, ready to be executed. In contrast, `iserv` has a loader for object and archive files. When dependencies need to be loaded into the interpreter, GHC just gives it the file name. Additionally, `iserv` contains a bytecode interpreter, which `thrunner` lacks.
```

2022-05-17 18:21 UTC, doyougnu requested changes
I made a bunch of comments, most of them minor with some re-architecting. Feel free to reject if it would take too much time to fix or you disagree with the change!

2022-05-17 18:21 UTC, doyougnu commented on blog/2022-05-17-javascript-template-haskell-ext-interp.md
> +The biggest change is that we have to rework the linker: `thrunner` does not contain any linking logic by itself: GHCJS compiles everything to JavaScript and sends compiled code to the `thrunner` pro
The last sentence `Additionally ...` isn't pertinent to the topic of the paragraph `The biggest change ... is the linker`. It seems like the beginning of a new paragraph that is missing. I would either delete it or write that paragraph. Right now its hard to know why you bring this up so if you add the new paragraph make sure to relate it to the changes we need to make, or state what we could do with it.

2022-05-17 18:21 UTC, doyougnu commented on blog/2022-05-17-javascript-template-haskell-ext-interp.md
> +Our plan is to have an `iserv` implementation that consists of a JavaScript part that runs in node.js and a proxy process to handle communication with GHC. The proxy process converts the messages bet
This seems like a good thing to me actually. What is the case where we don't know what was sent and expect a response?

I'm just curious this isn't really an edit request :)

2022-05-17 18:21 UTC, doyougnu commented on blog/2022-05-17-javascript-template-haskell-ext-interp.md
> +We have seen how Template Haskell and GHCi code can be run outside the GHC process for profiling or cross compiling, with both the `thrunner` approach in GHCJS and the newer `iserv` in GHC.
Aha! You should highlight these approaches explicitly with headers:

```
### Approach 1: The GHCJS approach, thrunner
....
So I went ahead and ...
...

### Approach 2: GHC's approach, iserv
Clearly it isn't ideal ....
...
```

Then you would need to change the paragraph after your TH list to name the approaches:

> The queries from the TH code are abstracted by the Quasi typeclass. I noticed that none of the methods required passing around functions or complicated data structures, so it would be possible to serialize each request and response and send it to another process. My initial approach was to write a script that does exactly this and is still how GHCJS works today, so I'll call it the `GHCJS Approach`.

and then you would have the next section for the `thrunner` right after this.

2022-05-24 07:33 UTC, luite commented on blog/2022-05-17-javascript-template-haskell-ext-interp.md
> +Our plan is to have an `iserv` implementation that consists of a JavaScript part that runs in node.js and a proxy process to handle communication with GHC. The proxy process converts the messages bet
The case is where we have a converting proxy. A simple stateless proxy could just handle the JSON <-> binary conversion without keeping track of state, possibly by just starting two independent `forkIO` threads (one for each direction). Unfortunately we have to write a more complicated stateful proxy here.

The `thrunner`/`iserv` process is always stateful, so there's no difference in complexity for that part of the system.

2022-05-24 07:34 UTC, luite commented on blog/2022-05-17-javascript-template-haskell-ext-interp.md
> +We have seen how Template Haskell and GHCi code can be run outside the GHC process for profiling or cross compiling, with both the `thrunner` approach in GHCJS and the newer `iserv` in GHC.
I've made it more clear in a few descriptions that `thrunner` ~ GHCJS approach and `iserv` ~ GHC approach.

2022-05-24 07:35 UTC, luite commented on blog/2022-05-17-javascript-template-haskell-ext-interp.md
> +The biggest change is that we have to rework the linker: `thrunner` does not contain any linking logic by itself: GHCJS compiles everything to JavaScript and sends compiled code to the `thrunner` pro
I've removed it

2022-05-24 07:37 UTC, luite commented on blog/2022-05-17-javascript-template-haskell-ext-interp.md
> +So I had to look for an alternative. Running Template Haskell basically consists of two parts:
sounds good / done

2022-05-24 07:39 UTC, luite commented on blog/2022-05-17-javascript-template-haskell-ext-interp.md
> +The queries from the TH code are abstracted by the `Quasi` typeclass. I noticed that none of the methods required passing around functions or complicated data structures, so it would be possible to s
I've a short paragraph for (1) and reworded a bit for (2)

2022-05-25 12:08 UTC, doyougnu requested changes
Just one suggested edit otherwise LGTM!

2022-05-31 11:40 UTC, merged